version: '3'

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build: .
    restart: always
    volumes:
      - ./public:/home/node/app/public:delegated
    ports:
      - 1337:1337